version: "3.8"
services:
  db:
    image: mongo
    container_name: ecomm-db
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    networks:
      - ecomm-net

  api:
    image: ecomm-img-api
    build:
      context: "./api"
      dockerfile: Dockerfile
    container_name: ecomm-api
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - ecomm-net

  ui:
    image: ecomm-img-ui
    build:
      context: "./ui"
      dockerfile: Dockerfile
    container_name: ecomm-ui
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - ecomm-net

  elasticsearch:
    container_name: ecomm-elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - ecomm-net
    ports:
      - 9200:9200

  kibana:
    container_name: ecomm-kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - ecomm-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

  # logstash:
  #   container_name: ecomm-logstash
  #   image: ecomm-img-logstash
  #   # image: docker.elastic.co/logstash/logstash:7.17.0
  #   build:
  #     context: "./logstash"
  #     dockerfile: Dockerfile
  #   environment:
  #     LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  #   ports:
  #     - "5044:5044"
  #     # - "5000:5000/tcp"
  #     # - "5000:5000/udp"
  #     - "9600:9600"
  #     # - "8080:8080"
  #   # volumes:
  #   #   - ./logstash/pipeline/:/usr/share/logstash/pipeline/
  #   networks:
  #     - ecomm-net
  #   depends_on:
  #     - elasticsearch

  monstache:
    image: rwynn/monstache:latest
    container_name: ecomm-monstache
    working_dir: /monstache
    command: -f ./config.toml
    volumes:
      - ./monstache:/monstache/
    ports:
      - "8080:8080"
    restart: always
    networks:
      - ecomm-net

networks:
  ecomm-net:
    driver: bridge
